[project]
name        = "rggen"
version     = "0.7.0"
authors     = ["Taichi Ishitani <taichi730@gmail.com>"]
license     = "MIT"
repository  = "https://github.com/rggen/rggen-veryl-rtl"

[format]
indent_width  = 2

[publish]
bump_commit    = true
publish_commit = true
